[package]
name    = "freeimage"
authors = [ "Arturo Castro <mail@arturocastro.net>" ]
description = "Rust idiomatic bindings for FreeImage"
license = "MIT"
homepage = "https://github.com/arturoc/freeimage-rs"
repository = "https://github.com/arturoc/freeimage-rs"
version = "0.0.2"

[lib]
name = "freeimage"
path = "src/lib.rs"

[target.i686-apple-darwin.dependencies]
freeimage-sys = "0.0.1"

[target.x86_64-apple-darwin.dependencies]
freeimage-sys = "0.0.1"

[dependencies]
libc = "0.2.*"
enum_primitive = "0.1.*"
num = "0.1.*"
